### ISSUE TITLE
Propane furnace replacement (SIR order for all measures, no promotion of HVAC measures before shell measures)

### ISSUE THREAD

**Issue by BrianaParrBaker** [fishbaugher/WAweb-Issues#86] opened 2024-04-01 15:34 UTC
This 78.4% efficient propane furnace had a 1.9 SIR in old WA but does not appear to meet SIR in WAweb. 

Recommended measures:
![oldWA](https://github.com/fishbaugher/WAweb-Issues/assets/162485966/aab5756e-25e0-43ff-9bb4-8c2bc449482a)
![WAweb](https://github.com/fishbaugher/WAweb-Issues/assets/162485966/a27e8d02-dedb-4021-92b1-155a84e5a29a)

HVAC pages:
![GGold](https://github.com/fishbaugher/WAweb-Issues/assets/162485966/19286d80-f3db-4007-b8ec-98d71b4a9bf8)
![image](https://github.com/fishbaugher/WAweb-Issues/assets/162485966/472efeee-c558-4b1e-a468-682fc08992e3)

**Comment by fishbaugher** [comment] 2024-04-02 09:16
This is HH 959750 and Audit 111623 in v8.x and 'Minnesota Valley Action Council Inc'. Audit ID 1102 on WAweb.

**Comment by fishbaugher** [comment] 2024-04-02 09:48
I suspect there are differences in the libraries.  One thing is that propane costs in v8.x were 2.50 while in WAweb they are 1.9.

I made a copy of the audit ((507) 317-6139 MJF Test) and entered the fuel costs to match 8.x.  That did not solve the problem.  The energy savings computed by v8.x is 24.4 MMBtu while in WAweb it is 9.9 MMBtu.
<img width="939" alt="Untitled 2" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/5996a095-1a12-4fbe-b689-5cb56065a3a7">
<img width="558" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/78a7fa8a-fe60-4ac4-bd7b-648d1a448f11">

I suspect this may have to do with the modeling order.  In WA v8.x the required furnace replacement measure is evaluated first on the uninsulated house (higher energy savings) while in v10.x it may be computing the interacted energy savings on the more efficient insulated house resulting in lower measure savings.

I have labeled this a repeatable bug for now, but that may change.

**Comment by fishbaugher** [comment] 2024-04-02 10:34
Confirmed.  In the un-interacted energy savings calculations, both engines produce ~25 MMBtu of savings from a furnace replacement.  In v8, the retrofit is required and promoted to the top of the interacted measure list producing:

<img width="919" alt="Untitled 2" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/fb0205f4-946b-454e-bf58-d4037e98d1ca">
while v10. there is no promotion and thus the measure is evaluated strictly in first-pass SIR order resulting in:

<img width="1233" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/dc3b47db-c78a-4f74-bd09-ead2a9e20a42">

Bill, correct us if we are wrong, but I think this is the new 'strictly in SIR order' policy and does not represent a bug.  Yes?

**Comment by eckmanwe** [comment] 2024-04-04 18:24
I'm not entirely certain what you mean by "new strictly in SIR order policy" means. However, I think you have covered it well. We are not longer allowed to force retrofits into the package earlier because they are "required", "mandatory", or air/duct sealing.

I believe that WA-MN NEAT #1125 clearly illustrates the required packaging methodology. Of additional note, even when selected with "Required" and "Include in SIR", WAweb will report the measure as an ECM if it meets the minimum SIR. If not, then as seen, it reports as an IRM. Similar is true if just "Required" is selected. Automatic ECM if cost-effective and HSM otherwise.

**Comment by fishbaugher** [comment] 2024-04-04 19:29
So, this is a procedure change with first order effects in MN where there are lots of HDD.  Heating savings of a baseline leaky shell have historically 'funded' the furnace change outs.  With the required/replacement being promoted in the second pass analysis.  This will take some getting used to and may have an impact with some furnace replacements no longer meeting SIR 1.0.

Since this no longer represents a bug, but rather a new normal analysis behavior, let's close this issue.  

I have modified the issue title hopefully to make this easy to spot in a search, because I am sure this is not the last time we will hear about changes to furnace replacement SIRs.

**Closed as completed by fishbaugher** 2024-04-04 19:29 UTC
Labels: Best practice, Priority High, EXPLAINED
